sudo: required
services:
  - docker

before_install:
  - docker image build -t keidrun/portfolio -f Dockerfile.dev .

script:
  - docker container run --rm keidrun/portfolio yarn lint

before_deploy:
  - docker container run -d --rm --name web keidrun/portfolio yarn dev
  - docker container exec -i web yarn build
  - docker container cp web:/app/build .

deploy:
  provider: s3
  region: us-east-1
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket: "keidrun-portfolio-website"
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
