FROM node:16-alpine

ENV GATSBY_TELEMETRY_DISABLED 1

WORKDIR /app

RUN apk update \
  && apk --no-cache add git ca-certificates wget curl

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY .flowconfig .
RUN yarn global add flow-typed \
  && flow-typed install

COPY . .

EXPOSE 8080

CMD yarn develop
