version: "3"

services:
  web:
    command: "yarn develop --host 0.0.0.0 --port 8080"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - .:/app
