FROM node:11.11-alpine

ENV GLIBC_VERSION=2.29-r0

WORKDIR /app

RUN apk update \
  && apk --no-cache add git ca-certificates wget

# Fix flow-bin issue(https://github.com/facebook/flow/issues/3649)
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-$GLIBC_VERSION.apk \
  && apk --no-cache add glibc-$GLIBC_VERSION.apk

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY .flowconfig .
RUN yarn global add flow-typed \
  && flow-typed install

COPY . .

EXPOSE 8080

CMD yarn dev
