export const btn: string
export const btnMainColor: string
export const skillItem: string
export const skillItemDescription: string
export const skillItemIcon: string
export const skillItemName: string
export const skillItemTitle: string
export const starRating: string
export const starRatingBack: string
export const starRatingFront: string
export const starRatingFrontStar00: string
export const starRatingFrontStar05: string
export const starRatingFrontStar10: string
export const starRatingFrontStar15: string
export const starRatingFrontStar20: string
export const starRatingFrontStar25: string
export const starRatingFrontStar30: string
export const starRatingFrontStar35: string
export const starRatingFrontStar40: string
export const starRatingFrontStar45: string
export const starRatingFrontStar50: string
