export const blue: string
export const btn: string
export const btnMainColor: string
export const green: string
export const orange: string
export const pink: string
export const portfolio: string
export const projectItem: string
export const projectItemCaption: string
export const projectItemDescription: string
export const projectItemFour: string
export const projectItemName: string
export const projectItemOne: string
export const projectItemThree: string
export const projectItemTitle: string
export const projectItemTwo: string
export const projectsGrid: string
export const projectsGridGut: string
export const projectsHover: string
export const purple: string
export const red: string
export const yellow: string
